Repository oVirt/ovirt-imageio, pull requests merged in 2022-07, with the labels that each got.

#103 Delete old files
  .gitreview
  .travis.yml
Labels: cleanup

#106 ovirt-img: Package as part of ovirt-imageio-client
  ovirt-imageio.spec.in
  setup.py
Labels: enhancement

#105 ovirt-img: Add logging options
  ovirt_imageio/client/_options.py
  ovirt_imageio/client/_ovirt.py
  ovirt_imageio/client/_tool.py
  test/client_options_test.py
Labels: enhancement

#110 client: Show progress phase
  ovirt_imageio/client/_ui.py
  test/client_ui_test.py
Labels: enhancement

#109 ovirt-img: fix logging config
  ovirt_imageio/client/_options.py
  ovirt_imageio/client/_ovirt.py
  test/client_options_test.py
Labels: bug

#114 ovirt-img: Add missing tests
  test/client_options_test.py
Labels: tests
