Repository oVirt/ovirt-imageio, pull requests merged in 2022-10, with the labels that each got.

#142 server: Make systemd optional
  examples/conf.d/daemon.conf
  ovirt_imageio/_internal/config.py
  ovirt_imageio/_internal/server.py
  test/conf.d/daemon.conf
  test/conf/daemon.conf
  test/conf/proxy.conf
  test/conf/user-tls.conf
Labels: enhancement

#138 ci: build containers automatically every week
  .github/workflows/containers.yml
Labels: enhancement

#150 Fix push to quay.io
  .github/workflows/containers.yml
Labels: build

#158 tox: Always disable sitepackages
  tox.ini
Labels: verified, tests
